### ISSUE TITLE
A Simple instruction for compile firmware

### ISSUE THREAD

**Issue by aleksey-su** [Appendme/android_device_lenovo_x2#2]
Hi 

I want to test your firmware. Haw I can compile its? Can you create simple instruction, please? 

Thanks!

**Comment by Appendme** [comment]
Здравствуйте.  
Я использую дерево от @xen0n(https://github.com/xen0n/local_manifests_arale/blob/cm-13.0/mtk.xml), конфликтов в общем-то нет. Только надо будет немного отредактировать, например external/sepolicy/domain.te, в нем убрать -proj_dev_setup так как я не использую [proj_dev_setup](https://github.com/xen0n/android_device_meizu_arale/tree/cm-13.0/proj-dev-setup).
Если нужна готовая прошивка то вот: https://yadi.sk/d/Owd2RO0DwWgDx .

**Comment by aleksey-su** [comment]
То есть можно воспользоваться любой инструкцией для компиляции, например этой http://androidp1.ru/sozdanie-cyanogenmod-proshivki-iz-ishodnogo-koda/? На этапе выбора устройства выбрать lunch cm_mx4-userdebug с поправками на  -proj_dev_setup и прошивка должна собраться.

Правильно?

**Comment by Appendme** [comment]
Не совсем. Где-то через 30-60 минут напишу.

**Comment by Appendme** [comment]
https://source.android.com/source/initializing.html
`sudo apt-get install openjdk-8-jdk` **для CM13**
`sudo apt-get install git-core gnupg flex bison gperf build-essential \
  zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
  lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
  libgl1-mesa-dev libxml2-utils xsltproc unzip maven repo schedtool`

```
mkdir ~/cm13.0
cd ~/cm13.0
git config --global user.name "aleksey-su"
git config --global user.email "email"
repo init -u git://github.com/CyanogenMod/android.git -b cm-13.0
```

После инициализации в папку ~/cm13.0/.repo/local_manifests киньте файл [mtk.xml](https://github.com/xen0n/local_manifests_arale/blob/cm-13.0/mtk.xml).
`repo sync`
Содержимое:
[android_device_lenovo_x2](https://github.com/Appendme/android_device_lenovo_x2) в ~/cm13.0/device/lenovo/x2eu
[android_vendor_lenovo_x2](https://github.com/Appendme/android_vendor_lenovo_x2) в ~/cm13.0/vendor/lenovo/x2eu
Команды для сборки(выполнять в папке ~/cm13.0):
`. build/envsetup.sh`
`lunch` //выбрать  cm_x2eu-\*  *-в сборке eng - adb будет включен сразу и нет авторизации.(в интернете можете найти информацию по подробнее)
`mka bacon` //на выходе при удачной сборке будет лежать архив в ~/cm13.0/out/target/product/x2eu

**Comment by aleksey-su** [comment]
Сейчас попробую. Спасибо! 

PS
Если нужна помощь, готов помочь проекту. Очень хочу избавится от двойного нажатия при наборе текста.

**Comment by Appendme** [comment]
Основная проблема пока только со связью, но думаю я нашел причину. Она скорее всего из-за этого:

> ifneq ($(X2_DEVICE),eu)
> MTK_SHARE_MODEM_CURRENT := 1
> MTK_SHARE_MODEM_SUPPORT := 1
> COMMON_GLOBAL_CFLAGS += \
>   -DMTK_SHARE_MODEM_CURRENT=1 \
>   -DMTK_SHARE_MODEM_SUPPORT=1 
> COMMON_GLOBAL_CPPFLAGS += \
>   -DMTK_SHARE_MODEM_CURRENT=1 \
>   -DMTK_SHARE_MODEM_SUPPORT=1 
> endif
> ifneq ($(X2_DEVICE),ap)
> MTK_SHARE_MODEM_CURRENT := 1
> MTK_SHARE_MODEM_SUPPORT := 2
> COMMON_GLOBAL_CFLAGS += \
>   -DMTK_SHARE_MODEM_CURRENT=1 \
>   -DMTK_SHARE_MODEM_SUPPORT=2
> COMMON_GLOBAL_CPPFLAGS += \
>   -DMTK_SHARE_MODEM_CURRENT=1 \
>   -DMTK_SHARE_MODEM_SUPPORT=2 
> endif

У кого-то прочитал здесь на гите, что если телефон односимочный то надо указать modem_support 1, сегодня попробую собрать под двухсимочный, если не заработает то буду сравнивать по совету xen0n'а. У него кстати телефон судя по обзорам односимочный, но он собирает под двухсим. Собственно поэтому думаю что проблема в этом.

**Comment by Appendme** [comment]
http://4pda.ru/forum/index.php?showtopic=667813&view=findpost&p=54409265 Связь пока запустили таким способом
